### PR TITLE
fix: check bridge always return success

### LINKED ISSUE #326: period handler (CheckBridge ABCI) always returns "success"
Observing on testnet and mainnet.

Invoice the work done on this issue to Ops Circle

### PR DESCRIPTION
**Pull request by troggy**
Due to the [bug](https://github.com/leapdao/tendermint/pull/10) in our tendermint fork, `chainHeight` is always 0 in a period handler. We didn't use it though for some reason and took block height from `chainInfo` instead. However, it was changed in April and we missed the fact that `chainHeight` is always 0, thus making checkBridge ABCI to always succeed without checking anything.

As a a side effect, all the CAS-related changes in period handler were never called and thus never tested in a wild.

Resolves #326 

- [x] make the height check work again
- [x] make period handler work with CAS 

## Solution for CAS

In checkBridge we don't want to check periods which don't have enough votes and hence not yet submitted.
I propose to track those as `pendingPeriod`.

Every 32nd block we want to:
1. keep the current period as `pendingPeriod` until we collect enough votes
2. start a new period right away

Once we collect enough period votes, we submit the pending period and it becomes `previousPeriod`.
The checkBridge code still tracks period submission via `previousPeriod`.

To illustrate:

`previousPeriod` — period in green
`pendingPeriod` — period in blue
`currentPeriod` — period in yellow

image

### CODE REVIEW

**Comment by troggy** [comment]
To illustrate:

`previousPeriod` — period in green
`pendingPeriod` — period in blue
`currentPeriod` — period in yellow

image

File: src/period/index.js [hunk 1]
```diff
@@ -11,22 +11,25 @@ const { logPeriod } = require('../utils/debug');
...
     return;
   }
 
-  logPeriod('checkBridge');
+  logPeriod('checkBridge. Period: ', bridgeState.previousPeriod.merkleRoot());
+
   // use a timeout to relax race conditions (if period submission is fast)
   await new Promise(resolve => {
     setTimeout(async () => {
-      await submitPeriodVote(bridgeState.previousPeriod, bridgeState, sender);
```
Comment (MaxStalker) [inline src/period/index.js]: Out of curiosity, I see that with this PR we haven't changed `\src\period\submitPeriodVote.js` - which expect 4 params, instead of 3. Was this code calling `submitPeriodVote` with wrong arguments? 🤔

File: src/period/index.js [hunk 2]
```diff
@@ -11,22 +11,25 @@ const { logPeriod } = require('../utils/debug');
 
 module.exports = (bridgeState, sender) => async (
   rsp,
-  chainInfo,
-  chainHeight
+  state,
+  chainInfo
```
Comment (troggy) [inline src/period/index.js]: not a rename, actually added a fourth argument (`state`) and stopped using one of the existing (`chainHeight`)
