### PR TITLE
invalid contract executions

### LINKED ISSUE #304: mismatched outputs when NFT not touched
## Bounty

mismatched outputs when NFT not touched.

### expected outputs

```
{"address":"0x9999999999999999999999999999999999999999","value":"456789","color":32769}
{"address":"0x9999999999999999999999999999999999999999","value":"987654","color":32769}
{"address":"0x9d058864a9a8ca23de5a42e4337aedba0582c0c4","value":"4993380102","color":0}
``` 
     
### received outputs:
```
{"address":"0x9999999999999999999999999999999999999999","value":"456789","color":32769}
{"address":"0x9d058864a9a8ca23de5a42e4337aedba0582c0c4","value":"4991404598","color":0}
```

## Scope

- fix failing unit test
- throw if NFT inputs are not touched in execution

## Deliverables

- code 
- integration tests

## Roles
TDD coding gardener: @johannbarbie / 10%
bounty worker: @johannbarbie  / 65%
bounty reviewer: @sunify  / 25%

### PR DESCRIPTION
**Pull request by johannbarbie**
resolves #304 
resolves https://github.com/leapdao/leap-node/issues/311

### CODE REVIEW

File: src/tx/applyTx/checkSpendCond.js [hunk 1]
```diff
@@ -455,7 +461,10 @@ module.exports = async (state, tx, bridgeState, nodeConfig = {}) => {
         // this hack assumes that an ERC1949 is minted
         // and that Transfer Event is emmited before UpdateData Event
         // so in only puts the new owner into the nftBag
-        nftBag[originAddr][`0x${topics[3].toString('hex')}`] = toAddr;
+        nftBag[originAddr][`0x${topics[3].toString('hex')}`] = {
```
Comment (sunify) [inline src/tx/applyTx/checkSpendCond.js]: Would be nice to extract `0x${topics[3].toString('hex')}` into variable:
1. The thing will have a name
2. It used more than 1 time

File: src/tx/applyTx/checkSpendCond.js [hunk 2]
```diff
@@ -480,6 +490,7 @@ module.exports = async (state, tx, bridgeState, nodeConfig = {}) => {
       }
     }
   });
+  // itterate over tokenBag, add all leftovers to outputs
   for (const originAddr in tokenBag) {
     if (Object.prototype.hasOwnProperty.call(tokenBag, originAddr)) {
```
Comment (sunify) [inline src/tx/applyTx/checkSpendCond.js]: Looks too verbose. `Object.entries(tokenBag).forEach` can work better:

```es6
Object.entries(tokenBag).forEach(([originAddr, originAmounts]) => {
  Object.entries(originAmounts[originAddr]).forEach(([owner, amount]) => {
    if (greaterThan(amount, BigInt(0))) {
      logOuts.push(new Output(amount, owner, deployed[originAddr]));
    }
  });
});
```

Or even extract iteration logic into helper (used twice):

```es6
const iterateBag = (tokenBag, cb) => {
  Object.entries(tokenBag).forEach(([originAddr, originAmounts]) => {
    Object.entries(originAmounts[originAddr]).forEach(([owner, value]) => {
      cb(originAddr, owner, value);
    });
  });
};

...

iterateBag(tokenBag, (originAddr, owner, amount) => {
  if (greaterThan(amount, BigInt(0))) {
    logOuts.push(new Output(amount, owner, deployed[originAddr]));
  }
})
```

**Comment by johannbarbie** [comment]
@sunify addressed them all, i think
