### PR TITLE
fix: replay submissions and restore period proposals on restart

### LINKED ISSUE #395: No period data in node database for replayed periods
# Bounty

*Given:*
- existing network with some period submitted at height X
- fresh node synced up with the network

*Expected:*
- call to `plasma_getPeriodByBlockHeight` for X returns period data

*Actual:*
- call to `plasma_getPeriodByBlockHeight` for X returns null

Root cause:
`plasma_getPeriodByBlockHeight` API uses period data stored in local node's db. This db is populated by scanning root chain for Submission events. During replay there are no period proposals hence when we have no height information for Submissions.

## Scope

- figure out a way to store period data during replays/resyncs
- implement and test it
- make sure there are no duplicates in the local database

## Deliverables

- updated code
- updated tests

## Gain for the project

usable JSON RPC for freshly synced nodes → ability to use it for proof generation

## Roles
bounty gardener: @troggy / 60 DAI
bounty worker: @troggy / 400 DAI
bounty reviewer: name / 90 DAI

## Funded by

Dev Circle

### PR DESCRIPTION
**Pull request by troggy**
This PR solves two problems: 

## 1. When replaying the chain, period submission are not saved to local db #395 

The goal here is the same: for every Submission event happened on root chain, we want a record in a local level db database for the node keeping the event data. We index these events by period start height, so that we can later query them via API for proof construction (https://github.com/leapdao/leap-node/pull/319).

## Changes overview:
- the node were batching all the Submissions in a transient variable (`bridgeState.submissions`) and saved those every block. Now it still collects submissions, but saves each submission individually once it is found onchain (during `submitPeriod` check).
- additionally we are indexing period data by period blocks root now, so that later we can check with db if the node saw the period already.
- the node doesn't allow multiple submissions for the same blocks anymore. We used to store an array of submissions per blocks interval, now it is just one submission. This submission can be overwritten with the one with different blocks root.

## Breaking changes
- plasma_getPeriodByBlockHeight returns object not array
- storing a single Period submission per period now. New submission for the same starting height will overwrite, unless having the same blocksRoot

## How to test
Use https://github.com/leapdao/leap-sandbox/pull/80 version of sandbox

1. Start a root chain
2. Start a single validator node, submit couple of periods
3. Start a second node
4. Check period data on the second node (e.g. using tool https://github.com/leapdao/leap-guardian/pull/39). Should be identical to the first node.

# 2. Period proposals were not restored correctly on node restart #382

Main changes to solve this:
- check if the period  was processed already or not by querying database (see `bridgeState. getPeriodDataByBlocksRoot`) instead of checking `lastPeriodRoot` only (when replayed it will always has the very last period root)
- store "last seen" period root in database and use it to recreate `currentPeriod` on restart. It is needed because we are not replaying the chain and bridge events from scratch anymore.

## How to test
Use https://github.com/leapdao/leap-sandbox/pull/80 version of sandbox

----

Fixes #395, #382 
Requires https://github.com/leapdao/leap-core/pull/171, https://github.com/leapdao/leap-sandbox/pull/80

### CODE REVIEW

File: src/api/createDb.js [hunk 1]
```diff
@@ -56,7 +56,8 @@ const createDb = levelDb => {
       .get(key)
       .then(jsonStr => {
         // hash, not object
-        if (jsonStr.indexOf('0x') === 0) return jsonStr;
+        if (jsonStr === null || jsonStr === undefined) return null;
```
Comment (troggy) [inline src/api/createDb.js]: unrelated change. Handling the situation when `null` is storred

File: src/api/methods/getPeriodByBlockHeight.js [hunk 2]
```diff
@@ -9,6 +9,6 @@ module.exports = async (bridgeState, db, heightOrTag) => {
   }
   const [periodStart, periodEnd] = Period.periodBlockRange(height);
   const periodData = await db.getPeriodData(periodStart);
-  if (!periodData) return null; // return null as Infura does
-  return periodData.map(d => ({ periodStart, periodEnd, ...d }));
+  if (!periodData) return null;
+  return { periodStart, periodEnd, ...periodData };
```
Comment (troggy) [inline src/api/methods/getPeriodByBlockHeight.js]: BREAKING: returning object instead of array now

File: src/api/createDb.js [hunk 3]
```diff
@@ -115,27 +116,34 @@ const createDb = levelDb => {
...
     );
+    // skip saving if record with the same root exists, otherwise overwrite
+    if (existingRecord && existingRecord.blocksRoot === submission.blocksRoot) {
+      return Promise.resolve();
+    }
+
+    const dbOpsBatch = levelDb.batch();
+    const key = `period!${periodStartHeight}`;
+    dbOpsBatch.put(`period!${submission.blocksRoot}`, key);
+    dbOpsBatch.put(key, JSON.stringify(submission));
```
Comment (troggy) [inline src/api/createDb.js]: storing a single submission per period now. New submission for the same starting height will overwrite, unless having the same blocksRoot

File: src/bridgeState.js [hunk 4]
```diff
@@ -299,34 +294,26 @@ module.exports = class BridgeState {
...
       periodProposal: this.periodProposal,
       stalePeriodProposal: this.stalePeriodProposal,
       lastSeenRootChainBlock: this.lastSeenRootChainBlock,
+      lastSeenBlocksRoot: this.lastBlocksRoot,
+      blockHeight: this.currentState.blockHeight,
     });
   }
 
-  async saveState() {
+  async saveConsensusState() {
```
Comment (troggy) [inline src/bridgeState.js]: renamed for clarity. This state is used by tendermint ABCI

**Comment by troggy** [comment]
Can be tested with this version of leap-sandbox: https://github.com/leapdao/leap-sandbox/pull/80

File: src/block/index.js [hunk 5]
```diff
@@ -50,6 +52,11 @@ module.exports = (bridgeState, db, nodeConfig = {}) => async (
   bridgeState.currentState = state;
   bridgeState.blockHeight = chainInfo.height;
 
-  await bridgeState.saveNodeState();
```
Comment (troggy) [inline src/block/index.js]: not saving proposal data every block. Instead saving every 32nd block (see `startNewPeriod`)

File: src/bridgeState.js [hunk 6]
```diff
@@ -225,10 +215,12 @@ module.exports = class BridgeState {
     ];
 
     const nodeState = (await this.db.getNodeState()) || {};
+    logVerbose(`Restored node state`, nodeState);
     this.periodProposal = nodeState.periodProposal || null;
     this.stalePeriodProposal = nodeState.stalePeriodProposal || null;
     this.lastSeenRootChainBlock =
       nodeState.rootChainBlockAtProposal || this.genesisBlockHeight;
+    this.blockHeight = nodeState.blockHeight;
```
Comment (troggy) [inline src/bridgeState.js]: `nodeState.blockHeight` is the plasma height at the time of period proposal creation. "period proposal creation" is every 32nd block, we are replaying from this point on every restart
