### PR TITLE
fix: allow to have many deposits in mempool

### LINKED ISSUE #134: allow to have more than one deposits in mem-pool
# Bounty

currently [this code](https://github.com/leapdao/leap-node/blob/master/src/tx/applyTx/checkDeposit.js) makes sure that that the deposit counter is strictly increasing against the state.
- when blocks are applied, that behavior is desired, to enforce strictly increasing deposits
- when a tx is entering the mem-pool, that behavior should allow to stack state changes on top of each other

`checkDeposit` increments deposit counter to process proper deposit event. The counter is stored in an app state (passed via `state` argument). `checkDeposit` is called by tendermint at least twice:
1. first, before it puts tx in a mempool. After that `state` will be reverted
2. second, when tx is being put in a block. State is not reverted

So if two deposit txs are being put in a mempool at the same time (e.g. during rescan of the bridge),`checkDeposit` will fail on a second tx because of incorrect counter in the state (remember, it is reverted all the time for mempool checks).

Issue is similar in nature to #405 

How to reproduce:
1. Start a root chain, don't start the leap-node
2. Make two or more deposits
3. Start the leap-node — it will fail to process all the deposits

Alternatively:
1. Make several deposits
2. Stop the leap-node and clear local data (`--fresh`) and start leap-node again — it will fail to process all the deposits

## Scope

- make checkDeposit to be idempotent — it should be possible to call it multiple times for the same tx with the same result (for `CheckTx` flow when state is being revert after the call)
- make sure at least these test scenarios pass:
  - start the chain, make two deposits, clean local data, restart the node → all deposits processed (likely in the same block)
  - chain is running, deposits are flowing one by one, one after another all making it to the plasma chain

## Deliverables

- updated code
- updated tests
- written report with scenarios tested

## Gain for the project

resilient deposits

## Roles
bounty gardener: @troggy / 50 DAI
bounty worker: @troggy / 85%
bounty reviewer: @TheReturnOfJan  / 15%

## Funded by

Dev Circle

### PR DESCRIPTION
**Pull request by troggy**
### What does this PR do?
Remove processedDeposit check from `checkDeposit` in favour of checking 
a) if deposit was seen on the root chain (is in `bridgeState.deposits`) 
b) if it wasn't processed already

Deposit is marked as processed by setting `included` attribute on it record in a bridgeState. Here we assume that node will always keep all the deposit records.

In order to set `included` just once, we are not passing `isCheck` into each tx handler. `isCheck` is `true` for `CheckTx` ABCI calls (which shouldn't change state and may be called multiple times) and `false` for `DeliverTx` ABCI.

### Recommendations for testing

How to reproduce:
- Start a root chain, don't start the leap-node
- Make two or more deposits
- Start the leap-node — it will fail to process all the deposits

Alternatively:
- Make several deposits
- Stop the leap-node and clear local data (--fresh) and start leap-node again — it will fail to process all the deposits

### Links to relevant issues or information
Fixes #134

### CODE REVIEW

File: src/tx/applyTx/checkDeposit.js [hunk 1]
```diff
@@ -9,40 +9,41 @@ const { Type } = require('leap-core');
...
-    !addrCmp(deposit.depositor, tx.outputs[0].address) ||
+    !equal(BigInt(deposit.amount), BigInt(value)) ||
+    Number(deposit.color) !== color ||
+    !addrCmp(deposit.depositor, address) ||
     // NFTs do not have data :)
-    (isNST(txColor) && deposit.data !== tx.outputs[0].data)
+    (isNST(color) && deposit.data !== data)
   ) {
-    throw new Error('Trying to submit incorrect deposit');
+    throw new Error(
```
Comment (TheReturnOfJan) [inline src/tx/applyTx/checkDeposit.js]: I like the expected/actual info. Probably very useful for debugging.
