### PR TITLE
fix(periods): submit only quorum of CAS signatures

### LINKED ISSUE #386: validator should submit only a minimum required set of signatures
# Bounty

Right now, validator creates CAS bitmap for all the signatures collected. E.g. in 4 validator setup, if all validators vote CAS btimap will have 4 bits set while quorum is just 3 sigs. Plasma bridge will reject such a bitmap by design (it is a simplest design to allow immediately remove period on challenge). We have to fix that.

## Scope

- change period submission logic to create CAS only for minimum required number of signatures. Even if more signatures collected, proposer should submit only minimum set.
- test this in > 2 validator setups

## Deliverables

- updated code
- updated tests

## Gain for the project

working period submissions

## Roles
bounty gardener: @troggy / 40 DAI
bounty worker: @troggy / 120 DAI
bounty reviewer: name / 40 DAI

## Funded by

Dev Circle

### PR DESCRIPTION
**Pull request by troggy**
Plasma bridge [requires](https://github.com/leapdao/leap-contracts/pull/264/files#diff-a1c254046ad1d0b9aadb7ff8be8273afR452) **strictly** a minimum amount of sigs to be submitted. Otherwise, reverts. This PR adjusts period submission for that.

Related: leapdao/meta#199

Resolves #386

### CODE REVIEW

**Comment by troggy** [comment]
testing with >2 slots..

File: src/validator/periods/submitPeriod.js [hunk 1]
```diff
@@ -75,7 +75,8 @@ module.exports = async (
     return defaultResponse;
   }
 
-  const cas = buildCas(periodProposal.votes);
+  const quorumOfVotes = periodProposal.votes.slice(0, needed);
```
Comment (johannbarbie) [inline src/validator/periods/submitPeriod.js]: nice naming 👏
